CREATE TABLE Promociones (
NUM_PROM NUMBER PRIMARY KEY,
TIPO_PROMOCION VARCHAR(100) NOT NULL,
FECHA_INICIO DATE,
FECHA_FINAL DATE,
ESTADO VARCHAR(25) NOT NULL,
PORCENTAJE INT NOT NULL,
Proveedor_Promocion NUMBER NOT NULL,
UNIDADES_VENDIDAS INT NOT NULL,
UNIDADES_DISPONIBLES INT NOT NULL,
CONSTRAINT fk_ProveedorPromocion FOREIGN KEY (Proveedor_Promocion) REFERENCES Proveedores(ID));

