CREATE TABLE Clientes (
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
CORREO VARCHAR(35) NOT NULL,
DIRECCION VARCHAR(30) NOT NULL,
COMPRA NUMBER NOT NULL,
CONSTRAINT fk_IdCompra_1 FOREIGN KEY (COMPRA) REFERENCES Compra(ID));