CREATE TABLE Estantes (
ID NUMBER PRIMARY KEY,
CANT_PRODUCTOS INT NOT NULL,
TIPO_PRODUCTO NUMBER NOT NULL,
CAPACIDAD INT NOT NULL,
OCUPADO INT NOT NULL,
SUCURSAL NUMBER NOT NULL,
CONSTRAINT fk_tip_prod FOREIGN KEY (TIPO_PRODUCTO) REFERENCES Tipo_Producto(ID),
CONSTRAINT fk_sucursal_estante FOREIGN KEY (SUCURSAL) REFERENCES Sucursales(ID))