CREATE TABLE Sucursales (
CIUDAD VARCHAR(25) NOT NULL,
DIRECCION VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
ID NUMBER PRIMARY KEY,
NIVEL_REORDEN INT NOT NULL,
RECOMPRA INT NOT NULL,
IdSupermercado NUMBER NOT NULL,
CONSTRAINT fk_Supermercado FOREIGN KEY (IdSupermercado) REFERENCES Supermercado(ID))

