DECLARE
    idprod int := 1;

UPDATE
    Productos
SET 
    p.EXISTENCIAS_ESTANTE = CASE WHEN e.CAPACIDAD<b.OCUPADO THEN p.EXISTENCIAS_ESTANTE + e.CAPACIDAD ELSE p.EXISTENCIAS_ESTANTE + b.OCUPADO END
    e.OCUPADO = CASE WHEN e.CAPACIDAD<b.OCUPADO THEN e.OCUPADO + e.CAPACIDAD ELSE e.OCUPADO + b.OCUPADO END
FROM 
    Productos p, Estantes e, Bodegas b
WHERE
    e.PRODUCTO = idprod, b.PRODUCTO = idprod
    

