INSERT INTO Proveedores
VALUES(123456,'SURTIFRUVER',4,'EXCLUSIVO');

INSERT INTO Proveedores
VALUES(278912,'SURTIABARROTES',4,'NOEXCLUSIVO');

INSERT INTO Proveedores
VALUES(389654,'SURTICARNES',5,'EXCLUSIVO');

INSERT INTO Proveedores
VALUES(474125,'LICORERAOFICIAL',3,'NOEXCLUSIVO');




