DROP TABLE Supermercado CASCADE CONSTRAINTS PURGE;

DROP TABLE Sucursales CASCADE CONSTRAINTS PURGE;

DROP TABLE Bodegas CASCADE CONSTRAINTS PURGE;

DROP TABLE Local_de_ventas CASCADE CONSTRAINTS PURGE;

DROP TABLE Estantes CASCADE CONSTRAINTS PURGE;

DROP TABLE Tipo_Producto CASCADE CONSTRAINTS PURGE;

DROP TABLE Productos CASCADE CONSTRAINTS PURGE;

DROP TABLE Productos_Perecederos CASCADE CONSTRAINTS PURGE;

DROP TABLE Abarrotes CASCADE CONSTRAINTS PURGE;

DROP TABLE Proveedores CASCADE CONSTRAINTS PURGE;

DROP TABLE Pedidos CASCADE CONSTRAINTS PURGE;

DROP TABLE Promociones CASCADE CONSTRAINTS PURGE;

DROP TABLE Clientes CASCADE CONSTRAINTS PURGE;

DROP TABLE Compra CASCADE CONSTRAINTS PURGE;

DROP TABLE Producto_Compra CASCADE CONSTRAINTS PURGE;

DROP TABLE Persona_Natural CASCADE CONSTRAINTS PURGE;

DROP TABLE Empresa CASCADE CONSTRAINTS PURGE;

DROP TABLE Usuario CASCADE CONSTRAINTS PURGE;

DROP TABLE Proveedores_Productos CASCADE CONSTRAINTS PURGE;

DROP TABLE Pedidos_Productos CASCADE CONSTRAINTS PURGE;

DROP TABLE Sucursales_Pedidos CASCADE CONSTRAINTS PURGE;

DROP TABLE Sucursales_Productos CASCADE CONSTRAINTS PURGE;

DROP TABLE Productos_Estantes CASCADE CONSTRAINTS PURGE;

DROP TABLE Productos_Bodegas CASCADE CONSTRAINTS PURGE;

DROP TABLE Proveedores_Sucursales CASCADE CONSTRAINTS PURGE;

DROP TABLE Bodegas_TipoProducto CASCADE CONSTRAINTS PURGE;