CREATE TABLE A_SUPERMERCADO (
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL
);


CREATE TABLE A_TIPO_PRODUCTO (
ID NUMBER PRIMARY KEY,
TIPO VARCHAR(25) NOT NULL,
CATEGORIA VARCHAR(25) NOT NULL);

CREATE TABLE A_PRODUCTOS (
NOMBRE VARCHAR(25) NOT NULL,
MARCA VARCHAR(25) NOT NULL,
PRECIO_UNITARIO FLOAT NOT NULL,
PRESENTACION VARCHAR(25) NOT NULL,
CANTIDAD_PRESENTACION VARCHAR(25) NOT NULL,
MEDIDA FLOAT NOT NULL,
EMPACADO VARCHAR(25) NOT NULL,
A_TIPO_PRODUCTO NUMBER NOT NULL,
CODIGO_BARRAS NUMBER PRIMARY KEY,
EXISTENCIAS_BODEGA INT NOT NULL,
EXISTENCIAS_ESTANTE INT NOT NULL,
CATEGORIA NUMBER NOT NULL,
FECHA_VENCIMIENTO DATE,
CONSTRAINT fk_Tipo_Producto_4 FOREIGN KEY (A_TIPO_PRODUCTO) REFERENCES A_TIPO_PRODUCTO(ID),
CONSTRAINT fk_Categoria FOREIGN KEY (CATEGORIA) REFERENCES A_TIPO_PRODUCTO(ID));

CREATE TABLE A_SUCURSALES (
CIUDAD VARCHAR(25) NOT NULL,
DIRECCION VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
ID NUMBER PRIMARY KEY,
NIVEL_REORDEN INT NOT NULL,
RECOMPRA INT NOT NULL,
IdSupermercado NUMBER NOT NULL,
IdProducto NUMBER NOT NULL,
CONSTRAINT fk_Supermercado FOREIGN KEY (IdSupermercado) REFERENCES A_SUPERMERCADO(ID),
CONSTRAINT fk_idProducto_7 FOREIGN KEY (IdProducto) REFERENCES A_PRODUCTOS(CODIGO_BARRAS));

CREATE TABLE A_BODEGAS (
ID NUMBER PRIMARY KEY,
CAPACIDAD FLOAT NOT NULL,
IdSucursal NUMBER NOT NULL,
OCUPADO INT NOT NULL,
IdProducto NUMBER NOT NULL,
CONSTRAINT fk_Sucursales FOREIGN KEY (IdSucursal) REFERENCES A_SUCURSALES(ID),
CONSTRAINT fk_idProducto_8 FOREIGN KEY (IdProducto) REFERENCES A_PRODUCTOS(CODIGO_BARRAS));

CREATE TABLE A_LOCAL_DE_VENTAS (
ID NUMBER PRIMARY KEY,
IdSucursal NUMBER NOT NULL,
CONSTRAINT fk_Sucursal FOREIGN KEY (IdSucursal) REFERENCES A_SUCURSALES(ID));

CREATE TABLE A_ESTANTES (
ID NUMBER PRIMARY KEY,
CANT_PRODUCTOS INT NOT NULL,
A_TIPO_PRODUCTO NUMBER NOT NULL,
CAPACIDAD INT NOT NULL,
OCUPADO INT NOT NULL,
SUCURSAL NUMBER NOT NULL,
CONSTRAINT fk_tip_prod FOREIGN KEY (A_TIPO_PRODUCTO) REFERENCES A_TIPO_PRODUCTO(ID),
CONSTRAINT fk_sucursal_estante FOREIGN KEY (SUCURSAL) REFERENCES A_SUCURSALES(ID));

CREATE TABLE A_PRODUCTOS_PERECEDEROS (
CodigoBarras NUMBER NOT NULL,
FECHA_VENCIMIENTO DATE,
A_TIPO_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_idProducto FOREIGN KEY (CodigoBarras) REFERENCES A_PRODUCTOS(CODIGO_BARRAS),
CONSTRAINT fk_Tipo_Producto FOREIGN KEY (A_TIPO_PRODUCTO) REFERENCES A_TIPO_PRODUCTO(ID));

CREATE TABLE A_ABARROTES (
CodigoBarras NUMBER NOT NULL,
A_TIPO_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_IDProduc FOREIGN KEY (CodigoBarras) REFERENCES A_PRODUCTOS(CODIGO_BARRAS),
CONSTRAINT fk_TIPO_Produc FOREIGN KEY (A_TIPO_PRODUCTO) REFERENCES A_TIPO_PRODUCTO(ID));

CREATE TABLE A_PROVEEDORES (
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
CALIDAD INT NOT NULL,
EXCLUSIVO VARCHAR(25));

CREATE TABLE A_PEDIDOS (
ID NUMBER PRIMARY KEY,
A_PRODUCTOS VARCHAR(25) NOT NULL,
VOLUMENES FLOAT NOT NULL,
PRECIO FLOAT NOT NULL,
FECHA DATE,
IdProveedor NUMBER NOT NULL,
CONSTRAINT fk_idProveedor FOREIGN KEY (IdProveedor) REFERENCES A_PROVEEDORES(ID));

CREATE TABLE A_PROMOCIONES (
NUM_PROM NUMBER PRIMARY KEY,
TIPO_PROMOCION VARCHAR(100) NOT NULL,
FECHA_INICIO DATE,
FECHA_FINAL DATE,
ESTADO VARCHAR(25) NOT NULL,
PORCENTAJE INT NOT NULL,
Proveedor_Promocion NUMBER NOT NULL,
UNIDADES_VENDIDAS INT NOT NULL,
UNIDADES_DISPONIBLES INT NOT NULL,
CONSTRAINT fk_ProveedorPromocion FOREIGN KEY (Proveedor_Promocion) REFERENCES A_PROVEEDORES(ID));

CREATE TABLE A_CLIENTES (
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
CORREO VARCHAR(35) NOT NULL,
DIRECCION VARCHAR(30) NOT NULL);

CREATE TABLE A_COMPRA (
ID NUMBER PRIMARY KEY,
PRECIO_COMPRA FLOAT NOT NULL,
FECHA DATE,
IDCLIENTE NUMBER NOT NULL,
CONSTRAINT fk_IdCliente  FOREIGN KEY (IDCLIENTE) REFERENCES A_CLIENTES(ID));

CREATE TABLE A_PRODUCTO_COMPRA (
CANTIDAD_PRODUCTO INT NOT NULL,
A_COMPRA NUMBER NOT NULL,
PRODUCTO NUMBER NOT NULL,
PROMOCION NUMBER NOT NULL,
CONSTRAINT fk_IdCompra  FOREIGN KEY (A_COMPRA) REFERENCES A_COMPRA(ID),
CONSTRAINT fk_IdProd  FOREIGN KEY (PRODUCTO) REFERENCES A_PRODUCTOS(CODIGO_BARRAS),
CONSTRAINT fk_IdProm FOREIGN KEY (PROMOCION) REFERENCES A_PROMOCIONES(NUM_PROM));

CREATE TABLE A_PERSONA_NATURAL (
CEDULA NUMBER NOT NULL,
CONSTRAINT fk_Cedula FOREIGN KEY (CEDULA) REFERENCES A_CLIENTES(ID));



CREATE TABLE A_EMPRESA (
NIT NUMBER NOT NULL,
CONSTRAINT fk_nit FOREIGN KEY (NIT) REFERENCES A_CLIENTES(ID));



CREATE TABLE A_USUARIO (
cedula NUMBER PRIMARY KEY,
nombre VARCHAR(25) NOT NULL,
tipo VARCHAR(15) NOT NULL,
SUCURSAL NUMBER NOT NULL,
CONSTRAINT fk_SUC FOREIGN KEY (SUCURSAL) REFERENCES A_SUCURSALES(ID));


CREATE TABLE A_PROVEEDORES_PRODUCTOS(
NIT_PROVEEDOR NUMBER NOT NULL,
ID_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_NIT_1 FOREIGN KEY (NIT_PROVEEDOR) REFERENCES A_PROVEEDORES(ID),
CONSTRAINT fk_ID_Producto_5 FOREIGN KEY (ID_PRODUCTO) REFERENCES A_PRODUCTOS(CODIGO_BARRAS));


CREATE TABLE A_PEDIDOS_PRODUCTOS (
ID_PEDIDOS NUMBER NOT NULL,
ID_PRODUCTOS NUMBER NOT NULL,
CONSTRAINT fk_ID_Pedido FOREIGN KEY (ID_PEDIDOS) REFERENCES A_PEDIDOS(ID),
CONSTRAINT fk_ID_Pr FOREIGN KEY (ID_PRODUCTOS) REFERENCES A_PRODUCTOS(CODIGO_BARRAS));

CREATE TABLE A_SUCURSALES_PEDIDOS (
ID_SUCURSAL NUMBER NOT NULL,
ID_PEDIDOS NUMBER NOT NULL,
CONSTRAINT fk_ID_SUC FOREIGN KEY (ID_SUCURSAL) REFERENCES A_SUCURSALES(ID),
CONSTRAINT fk_ID_PED FOREIGN KEY (ID_PEDIDOS) REFERENCES A_PEDIDOS(ID));


CREATE TABLE A_SUCURSALES_PRODUCTOS(
ID_SUCURSAL NUMBER NOT NULL,
ID_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_IDSucursales_1 FOREIGN KEY (ID_SUCURSAL) REFERENCES A_SUCURSALES(ID),
CONSTRAINT fk_IDProductos_1 FOREIGN KEY (ID_PRODUCTO) REFERENCES A_PRODUCTOS(CODIGO_BARRAS));


CREATE TABLE A_PRODUCTOS_ESTANTES(
ID_PRODUCTO NUMBER NOT NULL,
ID_ESTANTE NUMBER NOT NULL,
CONSTRAINT fk_ID_PRODUCTO_2 FOREIGN KEY (ID_PRODUCTO) REFERENCES A_PRODUCTOS(CODIGO_BARRAS),
CONSTRAINT fk_ID_ESTANTE_1 FOREIGN KEY (ID_ESTANTE) REFERENCES A_ESTANTES(ID));


CREATE TABLE A_PRODUCTOS_BODEGAS (
ID_PRODUCTO NUMBER NOT NULL,
ID_BODEGA NUMBER NOT NULL,
CONSTRAINT fk_ID_PRODUCTO_3 FOREIGN KEY (ID_PRODUCTO) REFERENCES A_PRODUCTOS(CODIGO_BARRAS),
CONSTRAINT fk_ID_BODEGA_1 FOREIGN KEY (ID_BODEGA) REFERENCES A_BODEGAS(ID));


CREATE TABLE A_PROVEEDORES_SUCURSALES (
NIT_PROVEEDOR NUMBER NOT NULL,
ID_SUCURSAL NUMBER NOT NULL,
CONSTRAINT fk_NIT_PROVEEDOR_1 FOREIGN KEY (NIT_PROVEEDOR) REFERENCES A_PROVEEDORES(ID),
CONSTRAINT fk_ID_SUCURSAL_1 FOREIGN KEY (ID_SUCURSAL) REFERENCES A_SUCURSALES(ID));


CREATE TABLE A_BODEGAS_TIPO_PRODUCTO (
ID_BODEGA NUMBER NOT NULL,
ID_TIPO_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_ID_BODEGA_2 FOREIGN KEY (ID_BODEGA) REFERENCES A_BODEGAS(ID),
CONSTRAINT fk_ID_TIPO_PRODUCTO_1 FOREIGN KEY (ID_TIPO_PRODUCTO) REFERENCES A_TIPO_PRODUCTO(ID));


COMMIT;
