CREATE TABLE Supermercado (
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL
);

CREATE TABLE Tipo_Producto (
ID NUMBER PRIMARY KEY,
TIPO VARCHAR(25) NOT NULL,
CATEGORIA VARCHAR(25) NOT NULL);

CREATE TABLE Productos (
NOMBRE VARCHAR(25) NOT NULL,
MARCA VARCHAR(25) NOT NULL,
PRECIO_UNITARIO FLOAT NOT NULL,
PRESENTACION VARCHAR(25) NOT NULL,
CANTIDAD_PRESENTACION VARCHAR(25) NOT NULL,
MEDIDA FLOAT NOT NULL,
EMPACADO VARCHAR(25) NOT NULL,
TIPO_PRODUCTO NUMBER NOT NULL,
CODIGO_BARRAS NUMBER PRIMARY KEY,
EXISTENCIAS_BODEGA INT NOT NULL,
EXISTENCIAS_ESTANTE INT NOT NULL,
CATEGORIA NUMBER NOT NULL,
FECHA_VENCIMIENTO DATE,
CONSTRAINT fk_Tipo_Producto_4 FOREIGN KEY (TIPO_PRODUCTO) REFERENCES Tipo_Producto(ID),
CONSTRAINT fk_Categoria FOREIGN KEY (CATEGORIA) REFERENCES Tipo_Producto(ID));

CREATE TABLE Sucursales (
CIUDAD VARCHAR(25) NOT NULL,
DIRECCION VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
ID NUMBER PRIMARY KEY,
NIVEL_REORDEN INT NOT NULL,
RECOMPRA INT NOT NULL,
IdSupermercado NUMBER NOT NULL,
IdProducto NUMBER NOT NULL,
CONSTRAINT fk_Supermercado FOREIGN KEY (IdSupermercado) REFERENCES Supermercado(ID),
CONSTRAINT fk_idProducto_7 FOREIGN KEY (IdProducto) REFERENCES Productos(CODIGO_BARRAS));

CREATE TABLE Bodegas (
ID NUMBER PRIMARY KEY,
CAPACIDAD FLOAT NOT NULL,
IdSucursal NUMBER NOT NULL,
OCUPADO INT NOT NULL,
IdProducto NUMBER NOT NULL,
CONSTRAINT fk_Sucursales FOREIGN KEY (IdSucursal) REFERENCES Sucursales(ID),
CONSTRAINT fk_idProducto_8 FOREIGN KEY (IdProducto) REFERENCES Productos(CODIGO_BARRAS));

CREATE TABLE Local_de_ventas (
ID NUMBER PRIMARY KEY,
IdSucursal NUMBER NOT NULL,
CONSTRAINT fk_Sucursal FOREIGN KEY (IdSucursal) REFERENCES Sucursales(ID));

CREATE TABLE Estantes (
ID NUMBER PRIMARY KEY,
CANT_PRODUCTOS INT NOT NULL,
TIPO_PRODUCTO NUMBER NOT NULL,
CAPACIDAD INT NOT NULL,
OCUPADO INT NOT NULL,
SUCURSAL NUMBER NOT NULL,
CONSTRAINT fk_tip_prod FOREIGN KEY (TIPO_PRODUCTO) REFERENCES Tipo_Producto(ID),
CONSTRAINT fk_sucursal_estante FOREIGN KEY (SUCURSAL) REFERENCES Sucursales(ID));

CREATE TABLE Productos_Perecederos (
CodigoBarras NUMBER NOT NULL,
FECHA_VENCIMIENTO DATE,
TIPO_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_idProducto FOREIGN KEY (CodigoBarras) REFERENCES Productos(CODIGO_BARRAS),
CONSTRAINT fk_Tipo_Producto FOREIGN KEY (TIPO_PRODUCTO) REFERENCES TIPO_PRODUCTO(ID));

CREATE TABLE Abarrotes (
CodigoBarras NUMBER NOT NULL,
Tipo_Producto NUMBER NOT NULL,
CONSTRAINT fk_IDProduc FOREIGN KEY (CodigoBarras) REFERENCES Productos(CODIGO_BARRAS),
CONSTRAINT fk_TIPO_Produc FOREIGN KEY (Tipo_Producto) REFERENCES Tipo_Producto(ID));

CREATE TABLE Proveedores (
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
CALIDAD INT NOT NULL,
EXCLUSIVO VARCHAR(25));

CREATE TABLE Pedidos (
ID NUMBER PRIMARY KEY,
PRODUCTOS VARCHAR(25) NOT NULL,
VOLUMENES FLOAT NOT NULL,
PRECIO FLOAT NOT NULL,
FECHA DATE,
IdProveedor NUMBER NOT NULL,
CONSTRAINT fk_idProveedor FOREIGN KEY (IdProveedor) REFERENCES Proveedores(ID));

CREATE TABLE Promociones (
NUM_PROM NUMBER PRIMARY KEY,
TIPO_PROMOCION VARCHAR(100) NOT NULL,
FECHA_INICIO DATE,
FECHA_FINAL DATE,
ESTADO VARCHAR(25) NOT NULL,
PORCENTAJE INT NOT NULL,
Proveedor_Promocion NUMBER NOT NULL,
UNIDADES_VENDIDAS INT NOT NULL,
UNIDADES_DISPONIBLES INT NOT NULL,
CONSTRAINT fk_ProveedorPromocion FOREIGN KEY (Proveedor_Promocion) REFERENCES Proveedores(ID));

CREATE TABLE Clientes (
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR(25) NOT NULL,
CORREO VARCHAR(35) NOT NULL,
DIRECCION VARCHAR(30) NOT NULL);

CREATE TABLE Compra (
ID NUMBER PRIMARY KEY,
PRECIO_COMPRA FLOAT NOT NULL,
FECHA DATE,
IDCLIENTE NUMBER NOT NULL,
CONSTRAINT fk_IdCliente  FOREIGN KEY (IDCLIENTE) REFERENCES Clientes(ID));

CREATE TABLE Producto_Compra (
CANTIDAD_PRODUCTO INT NOT NULL,
COMPRA NUMBER NOT NULL,
PRODUCTO NUMBER NOT NULL,
PROMOCION NUMBER NOT NULL,
CONSTRAINT fk_IdCompra  FOREIGN KEY (COMPRA) REFERENCES Compra(ID),
CONSTRAINT fk_IdProd  FOREIGN KEY (PRODUCTO) REFERENCES Productos(CODIGO_BARRAS),
CONSTRAINT fk_IdProm FOREIGN KEY (PROMOCION) REFERENCES Promociones(NUM_PROM));

CREATE TABLE Persona_Natural (
CEDULA NUMBER NOT NULL,
CONSTRAINT fk_Cedula FOREIGN KEY (CEDULA) REFERENCES Clientes(ID));

CREATE TABLE Empresa (
NIT NUMBER NOT NULL,
CONSTRAINT fk_nit FOREIGN KEY (NIT) REFERENCES Clientes(ID));

CREATE TABLE Usuario (
NUMERO_IDENTIFICACION NUMBER PRIMARY KEY,
TIPO_IDENTIFICACION VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
CORREO_ELECTRONICO VARCHAR(35) NOT NULL,
PALABRA_CLAVE VARCHAR(15) NOT NULL,
ROL VARCHAR(15) NOT NULL,
SUCURSAL NUMBER NOT NULL,
CONSTRAINT fk_SUC FOREIGN KEY (SUCURSAL) REFERENCES Sucursales(ID));

CREATE TABLE Proveedores_Productos(
NIT_PROVEEDOR NUMBER NOT NULL,
ID_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_NIT_1 FOREIGN KEY (NIT_PROVEEDOR) REFERENCES Proveedores(ID),
CONSTRAINT fk_ID_Producto_5 FOREIGN KEY (ID_PRODUCTO) REFERENCES Productos(CODIGO_BARRAS));

CREATE TABLE Pedidos_Productos (
ID_PEDIDOS NUMBER NOT NULL,
ID_PRODUCTOS NUMBER NOT NULL,
CONSTRAINT fk_ID_Pedido FOREIGN KEY (ID_PEDIDOS) REFERENCES Pedidos(ID),
CONSTRAINT fk_ID_Pr FOREIGN KEY (ID_PRODUCTOS) REFERENCES Productos(CODIGO_BARRAS));

CREATE TABLE Sucursales_Pedidos (
ID_SUCURSAL NUMBER NOT NULL,
ID_PEDIDOS NUMBER NOT NULL,
CONSTRAINT fk_ID_SUC FOREIGN KEY (ID_SUCURSAL) REFERENCES Sucursales(ID),
CONSTRAINT fk_ID_PED FOREIGN KEY (ID_PEDIDOS) REFERENCES Pedidos(ID));

CREATE TABLE Sucursales_Productos(
ID_SUCURSAL NUMBER NOT NULL,
ID_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_IDSucursales_1 FOREIGN KEY (ID_SUCURSAL) REFERENCES Sucursales(ID),
CONSTRAINT fk_IDProductos_1 FOREIGN KEY (ID_PRODUCTO) REFERENCES Productos(CODIGO_BARRAS));

CREATE TABLE Productos_Estantes(
ID_PRODUCTO NUMBER NOT NULL,
ID_ESTANTE NUMBER NOT NULL,
CONSTRAINT fk_ID_PRODUCTO_2 FOREIGN KEY (ID_PRODUCTO) REFERENCES Productos(CODIGO_BARRAS),
CONSTRAINT fk_ID_ESTANTE_1 FOREIGN KEY (ID_ESTANTE) REFERENCES Estantes(ID));

CREATE TABLE Productos_Bodegas (
ID_PRODUCTO NUMBER NOT NULL,
ID_BODEGA NUMBER NOT NULL,
CONSTRAINT fk_ID_PRODUCTO_3 FOREIGN KEY (ID_PRODUCTO) REFERENCES Productos(CODIGO_BARRAS),
CONSTRAINT fk_ID_BODEGA_1 FOREIGN KEY (ID_BODEGA) REFERENCES Bodegas(ID));

CREATE TABLE Proveedores_Sucursales (
NIT_PROVEEDOR NUMBER NOT NULL,
ID_SUCURSAL NUMBER NOT NULL,
CONSTRAINT fk_NIT_PROVEEDOR_1 FOREIGN KEY (NIT_PROVEEDOR) REFERENCES Proveedores(ID),
CONSTRAINT fk_ID_SUCURSAL_1 FOREIGN KEY (ID_SUCURSAL) REFERENCES Sucursales(ID));

CREATE TABLE Bodegas_TipoProducto (
ID_BODEGA NUMBER NOT NULL,
ID_TIPO_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_ID_BODEGA_2 FOREIGN KEY (ID_BODEGA) REFERENCES Bodegas(ID),
CONSTRAINT fk_ID_TIPO_PRODUCTO_1 FOREIGN KEY (ID_TIPO_PRODUCTO) REFERENCES Tipo_Producto(ID));

