CREATE TABLE Productos_Perecederos (
IdProducto NUMBER NOT NULL,
FECHA_VENCIMIENTO DATE,
TIPO_PRODUCTO NUMBER NOT NULL,
CONSTRAINT fk_idProducto FOREIGN KEY (IdProducto) REFERENCES Productos(ID),
CONSTRAINT fk_Tipo_Producto FOREIGN KEY (TIPO_PRODUCTO) REFERENCES TIPO_PRODUCTO(ID))

