DROP TABLE A_SUPERMERCADO CASCADE CONSTRAINTS PURGE;

DROP TABLE A_SUCURSALES CASCADE CONSTRAINTS PURGE;

DROP TABLE A_BODEGAS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_LOCAL_DE_VENTAS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_ESTANTES CASCADE CONSTRAINTS PURGE;

DROP TABLE A_TIPO_PRODUCTO CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PRODUCTOS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PRODUCTOS_PERECEDEROS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_ABARROTES CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PROVEEDORES CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PEDIDOS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PROMOCIONES CASCADE CONSTRAINTS PURGE;

DROP TABLE A_CLIENTES CASCADE CONSTRAINTS PURGE;

DROP TABLE A_COMPRA CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PRODUCTO_COMPRA CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PERSONA_NATURAL CASCADE CONSTRAINTS PURGE;

DROP TABLE A_EMPRESA CASCADE CONSTRAINTS PURGE;

DROP TABLE A_USUARIO CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PROVEEDORES_PRODUCTOS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PEDIDOS_PRODUCTOS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_SUCURSALES_PEDIDOS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_SUCURSALES_PRODUCTOS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PRODUCTOS_ESTANTES CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PRODUCTOS_BODEGAS CASCADE CONSTRAINTS PURGE;

DROP TABLE A_PROVEEDORES_SUCURSALES CASCADE CONSTRAINTS PURGE;

DROP TABLE A_BODEGAS_TIPO_PRODUCTO CASCADE CONSTRAINTS PURGE;

DROP TABLE A_CARRITO CASCADE CONSTRAINTS PURGE;

DROP TABLE A_CARRITO_PRODUCTO CASCADE CONSTRAINTS PURGE;
COMMIT;
