create sequence AforoAndes_sequence;


CREATE TABLE A_SUPERANDES
   (
	nombreempresa VARCHAR(200),
	nit INT,
	CONSTRAINT A_SUPERANDES PRIMARY KEY (nombreempresa)
    );
	
    
CREATE TABLE A_EMPLEADO
   (
	nombre VARCHAR(200),
	cedula INT,
    tipo VARCHAR(50),
    nombresupermercado VARCHAR(200),
	CONSTRAINT A_EMPLEADO PRIMARY KEY (cedula)
    );
	
ALTER TABLE A_EMPLEADO
ADD CONSTRAINT fk_a_superandes
    FOREIGN KEY (nombresupermercado)
    REFERENCES a_superandes(nombreempresa)
ENABLE;


CREATE TABLE A_PUNTOS
   (ID NUMBER, 
    TOTALPUNTOS NUMBER, 
    CONSTRAINT A_PUNTOS_PK PRIMARY KEY (ID));
    
CREATE TABLE A_CATEGORIA
   (NOMBRE VARCHAR2(255 BYTE),
    DESCRIPCION VARCHAR2(255 BYTE), 
    CONSTRAINT A_CATEGORIA_PK PRIMARY KEY (NOMBRE));




CREATE TABLE A_COMPRADOR
       (
	NOMBRE VARCHAR2(255 BYTE), 
    IDENTIFICACION VARCHAR2(255 BYTE), 
    DOCUMENTO NUMBER, 
    NIT NUMBER,
    CORREOELECTRONICO VARCHAR2(255 BYTE), 
    NOMBRESUPERMERCADO VARCHAR(200),
    DIRECCION VARCHAR(200),
    PUNTOS NUMBER,
	CONSTRAINT A_COMPRADOR_PK PRIMARY KEY (DOCUMENTO));
    
ALTER TABLE A_COMPRADOR
ADD CONSTRAINT fk_a_superandes
    FOREIGN KEY (nombresupermercado)
    REFERENCES a_superandes(nombreempresa)
ENABLE;

ALTER TABLE A_COMPRADOR
ADD CONSTRAINT fk_a_puntos
    FOREIGN KEY (puntos)
    REFERENCES A_PUNTOS(ID)
ENABLE;

CREATE TABLE A_FACTURA
   (
	ID NUMBER,
	TOTAL INT,
    NPRODUCTOS INT,
    PERSONA INT,
    FECHA VARCHAR(50),
    nombresupermercado VARCHAR(200),
	CONSTRAINT A_FACTURA_PK PRIMARY KEY (ID)
    );

ALTER TABLE A_FACTURA
ADD CONSTRAINT fk_a_comprador
    FOREIGN KEY (PERSONA)
    REFERENCES a_comprador(DOCUMENTO)
ENABLE;

ALTER TABLE A_FACTURA
ADD CONSTRAINT fk_a_superandes
    FOREIGN KEY (nombresupermercado)
    REFERENCES a_superandes(nombreempresa)
ENABLE;



CREATE TABLE A_SUCURSAL
   (
    TOTALVENTAS INT,
	AREA INT,
    CIUDAD VARCHAR(50),
    NOMBRE VARCHAR(50),
    DIRECCION VARCHAR(50),
    nombresupermercado VARCHAR(200),
	CONSTRAINT A_SUCURSAL_PK PRIMARY KEY (NOMBRE)
    );
    
ALTER TABLE A_SUCURSAL
ADD CONSTRAINT fk_a_superandes
    FOREIGN KEY (nombresupermercado)
    REFERENCES a_superandes(nombreempresa)
ENABLE;

CREATE TABLE A_BODEGA
   (
    CAPACIDAD INT,
	CAPACIDADACTUAL INT,
   	ID NUMBER,
    sucursal VARCHAR(200),
	CONSTRAINT A_BODEGA_PK PRIMARY KEY (ID)
    );
ALTER TABLE A_BODEGA
ADD CONSTRAINT fk_a_sucursal
    FOREIGN KEY (sucursal)
    REFERENCES a_sucursal(NOMBRE)
ENABLE;
    

CREATE TABLE A_PROVEEDOR
   (
    NIT INT,
	CALIFICACIONDECALIDAD INT,
    nombresupermercado VARCHAR(200),
    NOMBRE VARCHAR(200),
	CONSTRAINT A_PROVEEDOR_PK PRIMARY KEY (NIT)
    );

ALTER TABLE A_PROVEEDOR
ADD CONSTRAINT fk_a_superandes
    FOREIGN KEY (nombresupermercado)
    REFERENCES a_superandes(nombreempresa)
ENABLE;



CREATE TABLE A_ESTANTE
   (
   	ID NUMBER,
    CAPACIDAD INT,
	NIVELDEABASTECIMIENTO INT,
    NOMBRESUCURSAL VARCHAR(200),
    CATEGORIA VARCHAR(200),
    CODIGOBODEGA INT,
	CONSTRAINT A_ESTANTE_PK PRIMARY KEY (ID)
    );

ALTER TABLE A_ESTANTE
ADD CONSTRAINT fk_a_sucursal
    FOREIGN KEY (NOMBRESUCURSAL)
    REFERENCES a_sucursal(NOMBRE)
ENABLE;

ALTER TABLE A_ESTANTE
ADD CONSTRAINT fk_a_categoria
    FOREIGN KEY (CATEGORIA)
    REFERENCES a_categoria(NOMBRE)
ENABLE;

ALTER TABLE A_ESTANTE
ADD CONSTRAINT fk_a_bodega
    FOREIGN KEY (CODIGOBODEGA)
    REFERENCES a_bodega(ID)
ENABLE;


CREATE TABLE A_PROMOCION
   (
   	ID NUMBER,
    DESCUENTO INT,
	FECHA  VARCHAR(200),
    NOMBREDESUCURSAL VARCHAR(200),

	CONSTRAINT A_PROMOCION_PK PRIMARY KEY (ID)
    );
    
ALTER TABLE A_PROMOCION
ADD CONSTRAINT fk_a_sucursal
    FOREIGN KEY (NOMBREDESUCURSAL)
    REFERENCES a_sucursal(NOMBRE)
ENABLE;

CREATE TABLE A_PRODUCTO
   (
   	CODIGODEBARRA INT,
    TOTALEXISTENCIAS INT,
    REORDEN INT,
    PRECIOUNITARIO INT,
    PRECIOPORUNIDADDEMEDIDA INT,
    UNIDADDEMEDIDA VARCHAR(200),
	MARCA  VARCHAR(200),
    ESPECIFICACIONDEMEDIDA  VARCHAR(200),
    NOMBRE  VARCHAR(200),
    NOMBREDESUCURSAL VARCHAR(200),
    
    IDFACTURA INT,
    NOMBRECATEGORIA VARCHAR(200),
    IDESTANTE INT,
    IDBODEGA INT,
    IDPROMOCION INT,
	CONSTRAINT A_PRODUCTO_PK PRIMARY KEY (CODIGODEBARRA)
    );
    
ALTER TABLE A_PRODUCTO
ADD CONSTRAINT fk_a_factura
    FOREIGN KEY (IDFACTURA)
    REFERENCES a_factura(ID)
ENABLE;

ALTER TABLE A_PRODUCTO
ADD CONSTRAINT fk_a_categoria
    FOREIGN KEY (NOMBRECATEGORIA)
    REFERENCES a_categoria(NOMBRE)
ENABLE;

ALTER TABLE A_PRODUCTO
ADD CONSTRAINT fk_a_estante
    FOREIGN KEY (IDESTANTE)
    REFERENCES a_estante(ID)
ENABLE;

ALTER TABLE A_PRODUCTO
ADD CONSTRAINT fk_a_bodega
    FOREIGN KEY (IDBODEGA)
    REFERENCES a_bodega(ID)
ENABLE;

ALTER TABLE A_PRODUCTO
ADD CONSTRAINT fk_a_promocion
    FOREIGN KEY (IDPROMOCION)
    REFERENCES a_promocion(ID)
ENABLE;


COMMIT;

